### ISSUE TITLE
Should the version number of the release match that of each protocol?

### ISSUE THREAD

**Issue by lukenoaa** [aomlomics/protocols#14]
Or can the protocols have different version numbers from the GitHub release version number?

For example, a current protocol is v1.0.1 but the GitHub release is v1.0.0. This might create confusion. If we make them uniform, we need to version every protocol (edit its Markdown file in the version section) each time we make a new release.

**Comment by lukenoaa** [comment]
@ksilnoaa Thoughts on this?

Alternatively, we could name the releases with the date, eg `2024-11-26` instead of `v1.0.0`.

**Comment by ksilnoaa** [comment]
I don't think you should update each protocol's version number just because the repo version updated. I don't think people will be that confused if the numbers don't match, but if you are worried I think it makes sense to use date for the github repo version. 

I think this is why PMEL put [each protocol in it's own repo](https://github.com/NOAA-PMEL/Ocean-Molecular-Ecology#pcr-protocols) and had a central repo for links, but I like that all of our are together.

**Comment by lukenoaa** [comment]
I cringe a bit looking at PMEL's repo and file names. I'll go with dates for future releases.
